docker image

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -47,4 +47,33 @@ jobs:
       with:
         name: model-metrics-report
         path: mlflow_report.csv
-        
+    - name: Evaluation and Model Accuracy Check
+      run: |
+        #csv file is generated by publish_metrics.py and contains a column named "accuracy"
+        accuracy=$(awk -F, 'NR>1 {print $2}' mlflow_report.csv)
+        echo "Model Accuracy: $accuracy"
+        if (( $(echo "$accuracy < ${{vars.ACCURACY_THRESHOLD}}" | bc -l) )); then
+          echo "Model accuracy is below threshold. Failing the build."
+          exit 1
+        else
+          echo "Model accuracy is above threshold. Build passed."
+        fi
+    - name: unit test cases
+      run: |
+        pytest -v
+    - name: Build Docker Image
+      run: |
+        docker build -t mlops-app .
+    - name: Scan Docker Image for Vulnerabilities
+      uses: aquasecurity/trivy-action@master
+      with:
+        image-ref: mlops-app:latest
+    - name: Push Docker Image to Docker Hub
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        push: true
+        tags: ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
